---
- name: Create Bastion Host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/output_vars

    - name: Import bastion host variables
      include_vars: vars/bastion_setup

    - name: Create a keypair
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save pem file to bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Security group for bastion host
      ec2_group:
        name: bastion-host-sg
        description: Allow port 22 from everywhere and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out
    - name: Creating Bastion Host EC2 Instance
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        resource_tags:
          Name: "Bastion_Host"
          Project: "vprofile"
          Owner: prakash
        exact_count: 1
        count_tag:
          Name: "Bastion_Host"
          Project: "vprofile"
          Owner: prakash
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out
