- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_hostnames: true
        dns_support: true
        tenancy: default
      register: vpcout
    #    - debug:
    #        var: vpcout
    - name: Create Public Subnet in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: true
        az: "{{Zone1}}"
        resource_tags:
          Name: vprofile-PubSub1
      register: pubsub1_out
    - name: Create Public Subnet in Zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: true
        az: "{{Zone2}}"
        resource_tags:
          Name: vprofile-PubSub2
      register: pubsub2_out
    - name: Create Public Subnet in Zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: true
        az: "{{Zone3}}"
        resource_tags:
          Name: vprofile-PubSub3
      register: pubsub3_out
