- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_hostnames: true
        dns_support: true
        tenancy: default
      register: vpcout
    - debug:
        vars: vpcout
    - name: Create Public Subnet in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: true
        az: "{{Zone1}}"
        resource_tags:
          name: vprofile-PubSub1
        register: pubsub1_out
